name: Run Python script

on:
  schedule:
    - cron: '23 23 * * *' # 北京时间减8小时

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Python 版本

      - name: Install dependencies
        run: pip install -r requirements.txt # 依赖文件路径

      - name: Run Python script
        run: python szy.py # py文件路径
